// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY39HDBqnSe-SC101xp2CFw3PkIHLza_k',
    appId: '1:336725110525:android:8838c5cfa3d295413d1894',
    messagingSenderId: '336725110525',
    projectId: 'inventory-manager-a5bc5',
    storageBucket: 'inventory-manager-a5bc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYLPWjTi905eMQ6VkE0_l2rikrYiXWM9w',
    appId: '1:336725110525:ios:ffff661ecebb59f93d1894',
    messagingSenderId: '336725110525',
    projectId: 'inventory-manager-a5bc5',
    storageBucket: 'inventory-manager-a5bc5.firebasestorage.app',
    iosBundleId: 'com.example.smartFitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYLPWjTi905eMQ6VkE0_l2rikrYiXWM9w',
    appId: '1:336725110525:ios:ffff661ecebb59f93d1894',
    messagingSenderId: '336725110525',
    projectId: 'inventory-manager-a5bc5',
    storageBucket: 'inventory-manager-a5bc5.firebasestorage.app',
    iosBundleId: 'com.example.smartFitnessApp',
  );
}
