// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi-dsyIkHLS39qJMK_dSKYziYvYne_cwI',
    appId: '1:846498076999:android:02502f3dfbd8c17401d462',
    messagingSenderId: '846498076999',
    projectId: 'smartfitness-dfb87',
    storageBucket: 'smartfitness-dfb87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsCouPtnBR1GivnmduY11YFOSNIBjgj8c',
    appId: '1:846498076999:ios:127a34e09cdb781901d462',
    messagingSenderId: '846498076999',
    projectId: 'smartfitness-dfb87',
    storageBucket: 'smartfitness-dfb87.firebasestorage.app',
    iosBundleId: 'com.example.smartFitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsCouPtnBR1GivnmduY11YFOSNIBjgj8c',
    appId: '1:846498076999:ios:127a34e09cdb781901d462',
    messagingSenderId: '846498076999',
    projectId: 'smartfitness-dfb87',
    storageBucket: 'smartfitness-dfb87.firebasestorage.app',
    iosBundleId: 'com.example.smartFitnessApp',
  );

}