import 'package:dio/dio.dart';
import '../domain/workout_models.dart';
import '../../../features/exercises/domain/exercise_models.dart';

/// Service for interacting with AI to generate workout plans
abstract class AIWorkoutService {
  Future<AIGeneratedWorkout> generateWorkout(String userMessage, List<Exercise> availableExercises);
}

class GeminiAIWorkoutService implements AIWorkoutService {
  final Dio _dio;
  final String apiKey;
  final String baseUrl;

  GeminiAIWorkoutService({
    required this.apiKey,
    required this.baseUrl,
  }) : _dio = Dio();

  @override
  Future<AIGeneratedWorkout> generateWorkout(
    String userMessage,
    List<Exercise> availableExercises,
  ) async {
    try {
      // Create a context with available exercises
      final systemPrompt = _createSystemPrompt(availableExercises);
      final fullMessage = '$systemPrompt\n\nUser Request: $userMessage';

      final response = await _dio.post(
        '$baseUrl/generate-workout',
        data: {
          'message': fullMessage,
        },
        options: Options(
          headers: {
            'Content-Type': 'application/json',
          },
        ),
      );

      if (response.statusCode == 200) {
        final data = response.data as Map<String, dynamic>;
        final message = data['message'] as String? ?? 'Generated workout';
        final planData = data['plan'] as Map<String, dynamic>?;

        if (planData != null) {
          final plan = _parseAIPlan(planData);
          return AIGeneratedWorkout(message: message, plan: plan);
        }

        return AIGeneratedWorkout(message: message);
      }

      throw Exception('Failed to generate workout: ${response.statusCode}');
    } catch (e) {
      return AIGeneratedWorkout(
        message: 'Failed to generate workout. Please try again or create a workout manually.',
      );
    }
  }

  String _createSystemPrompt(List<Exercise> availableExercises) {
    final exercisesInfo = availableExercises
        .take(100) // Limit to 100 exercises to avoid token limits
        .map((e) => '- ${e.name} (${e.muscle ?? "full body"})')
        .join('\n');

    return '''
You are an expert fitness trainer. Generate personalized workout plans based on user requests.

Available Exercises:
$exercisesInfo

Generate workouts in the following JSON format:
{
  "title": "Workout Title",
  "description": "Brief description",
  "exercises": [
    {
      "exerciseId": "exercise_uuid",
      "exerciseName": "Exercise Name",
      "orderIndex": 0,
      "restSeconds": 60,
      "sets": [
        {"reps": 10, "weight": null, "durationSeconds": null}
      ]
    }
  ]
}

Guidelines:
- Provide 3-8 exercises per workout
- Set appropriate reps (typically 8-15 for strength, 15-20 for endurance)
- Include rest periods between sets (30-180 seconds)
- Match exercise selection to user's goals and fitness level
- Use exercises from the available list

User Request:''';
  }

  WorkoutPlan _parseAIPlan(Map<String, dynamic> planData) {
    // This would parse the AI response into a WorkoutPlan
    // For now, returning a placeholder
    // In production, you'd want robust JSON parsing with error handling
    
    final exercisesData = planData['exercises'] as List?;
    final exercises = <WorkoutExercise>[];

    for (int i = 0; i < (exercisesData?.length ?? 0); i++) {
      final exData = exercisesData![i] as Map<String, dynamic>;
      final setsData = exData['sets'] as List?;
      final sets = (setsData ?? [])
          .map((s) => ExerciseSet(
                id: '', // Will be generated by database
                workoutExerciseId: '',
                reps: s['reps'] as int?,
                weight: s['weight'] as double?,
                durationSeconds: s['durationSeconds'] as int?,
              ))
          .toList();

      exercises.add(WorkoutExercise(
        id: '', // Will be generated by database
        workoutPlanId: '',
        exerciseId: exData['exerciseId'] as String? ?? '',
        exerciseName: exData['exerciseName'] as String? ?? 'Exercise',
        orderIndex: i,
        sets: sets,
        restSeconds: exData['restSeconds'] as int? ?? 60,
      ));
    }

    return WorkoutPlan(
      id: '', // Will be generated
      title: planData['title'] as String? ?? 'AI Generated Workout',
      description: planData['description'] as String?,
      userId: '', // Will be set by the repository
      createdAt: DateTime.now(),
      isAIGenerated: true,
      exercises: exercises,
    );
  }
}

/// Local mock service for development/testing
class MockAIWorkoutService implements AIWorkoutService {
  @override
  Future<AIGeneratedWorkout> generateWorkout(
    String userMessage,
    List<Exercise> availableExercises,
  ) async {
    // Simulate network delay
    await Future.delayed(const Duration(seconds: 2));

    // Return a mock workout
    final plan = WorkoutPlan(
      id: '',
      title: 'AI Generated Workout',
      description: 'Generated based on your request: $userMessage',
      userId: '',
      createdAt: DateTime.now(),
      isAIGenerated: true,
      exercises: availableExercises.take(5).toList().asMap().entries.map((entry) {
        final exercise = entry.value;
        return WorkoutExercise(
          id: '',
          workoutPlanId: '',
          exerciseId: exercise.id,
          exerciseName: exercise.name,
          orderIndex: entry.key,
          sets: List.generate(
            3,
            (i) => ExerciseSet(
              id: '',
              workoutExerciseId: '',
              reps: 12,
              weight: null,
            ),
          ),
          restSeconds: 60,
        );
      }).toList(),
    );

    return AIGeneratedWorkout(
      message: 'I\'ve created a personalized workout plan based on your request!',
      plan: plan,
    );
  }
}

